web/router.ex
defmodule Registering.Router do
  use Registering.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Registering do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/drivers", DriverController do
      resources "/vehicles", VehicleController
    end
    get "/vehicles", VehicleController, :list
  end

  # Other scopes may use custom stacks.
  # scope "/api", Registering do
  #   pipe_through :api
  # end
end

lib/registering/endpoint.ex
defmodule Registering.Endpoint do
  use Phoenix.Endpoint, otp_app: :registering

  socket "/socket", Registering.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :registering, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_registering_key",
    signing_salt: "GZzu5cxL"

  plug Registering.Router
end

lib/registering/repo.ex
defmodule Registering.Repo do
  use Ecto.Repo, otp_app: :registering
end

web/models/driver.ex
defmodule Registering.Driver do
  use Registering.Web, :model

  schema "drivers" do
    has_many :vehicles, Registering.Vehicle
    field :name, :string
    field :identification, :string

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :identification])
    |> validate_required([:name, :identification])
  end
end

web/models/vehicle.ex
defmodule Registering.Vehicle do
  use Registering.Web, :model

  schema "vehicles" do
    belongs_to :driver, Registering.Driver
    field :license_plate, :string
    field :brand, :string
    field :kind, :string

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:license_plate, :brand, :kind])
    |> validate_required([:license_plate, :brand, :kind])
  end
end

web/controllers/driver_controller.ex
defmodule Registering.DriverController do

  use Registering.Web, :controller

  alias Registering.Helpers

  alias Registering.Driver

  def index(conn, params) do
    drivers = Helpers.search(params, Driver)
    render(conn, "index.html", drivers: drivers)
  end

  def new(conn, _params) do
    changeset = Driver.changeset(%Driver{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"driver" => driver_params}) do
    changeset = Driver.changeset(%Driver{}, driver_params)

    case Repo.insert(changeset) do
      {:ok, driver} ->
        conn
        |> put_flash(:info, "Driver created successfully.")
        |> redirect(to: driver_path(conn, :show, driver))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    driver = Repo.get!(Driver, id)
    render(conn, "show.html", driver: driver)
  end

  def edit(conn, %{"id" => id}) do
    driver = Repo.get!(Driver, id)
    changeset = Driver.changeset(driver)
    render(conn, "edit.html", driver: driver, changeset: changeset)
  end

  def update(conn, %{"id" => id, "driver" => driver_params}) do
    driver = Repo.get!(Driver, id)
    changeset = Driver.changeset(driver, driver_params)

    case Repo.update(changeset) do
      {:ok, driver} ->
        conn
        |> put_flash(:info, "Driver updated successfully.")
        |> redirect(to: driver_path(conn, :show, driver))
      {:error, changeset} ->
        render(conn, "edit.html", driver: driver, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    driver = Repo.get!(Driver, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(driver)

    conn
    |> put_flash(:info, "Driver deleted successfully.")
    |> redirect(to: driver_path(conn, :index))
  end
end

web/controllers/page_controller.ex
defmodule Registering.PageController do
  use Registering.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/vehicle_controller.ex
defmodule Registering.VehicleController do
  use Registering.Web, :controller

  alias Registering.Helpers

  alias Registering.Vehicle

  plug :find_user, "before all but list" when not action in [:list]

  defp find_user(conn, _) do
    driver = Repo.get(Registering.Driver, conn.params["driver_id"])
    assign(conn, :driver, driver)
  end

  def list(conn, params) do
    vehicles = Helpers.search(params, Vehicle)
    render(conn, "list.html", vehicles: vehicles)
  end

  def index(conn, _params) do
    driver = conn.assigns.driver
    vehicles = Repo.all assoc(driver, :vehicles)

    render conn, vehicles: vehicles, driver: driver
  end

  def new(conn, _params) do
    changeset =
      conn.assigns.driver
      |> build_assoc(:vehicles)
      |> Vehicle.changeset()

    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"vehicle" => vehicle_params}) do
    changeset =
      conn.assigns.driver
      |> build_assoc(:vehicles)
      |> Vehicle.changeset(vehicle_params)

    case Repo.insert(changeset) do
      {:ok, _vehicle} ->
        conn
        |> put_flash(:info, "Vehicle created successfully.")
        |> redirect(to: driver_vehicle_path(conn, :index, conn.assigns.driver))
      {:error, _vehicle} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

web/views/driver_view.ex
defmodule Registering.DriverView do
  use Registering.Web, :view
end

web/views/error_view.ex
defmodule Registering.ErrorView do
  use Registering.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Registering.LayoutView do
  use Registering.Web, :view
end

web/views/page_view.ex
defmodule Registering.PageView do
  use Registering.Web, :view
end

web/views/vehicle_view.ex
defmodule Registering.VehicleView do
  use Registering.Web, :view

end

web/templates/driver/edit.html.eex
<h2>Edit driver</h2>

<%= render "form.html", changeset: @changeset,
                        action: driver_path(@conn, :update, @driver) %>

<span><%= link "Back", to: driver_path(@conn, :index) %></span>

web/templates/driver/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :identification, class: "control-label" %>
    <%= text_input f, :identification, class: "form-control" %>
    <%= error_tag f, :identification %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/driver/index.html.eex
<h2>Listing drivers</h2>
<%= form_for @conn, driver_path(@conn, :index), [method: :get], fn f -> %>
  <%= text_input f, :name, placeholder: "Search by Name" %>
<% end %>
<%= form_for @conn, driver_path(@conn, :index), [method: :get], fn f -> %>
  <%= text_input f, :identification, placeholder: "Search by ID" %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Identification</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for driver <- @drivers do %>
    <tr>
      <td><%= driver.name %></td>
      <td><%= driver.identification %></td>

      <td class="text-right">
        <span><%= link "Show", to: driver_path(@conn, :show, driver), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: driver_path(@conn, :edit, driver), class: "btn btn-default btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New driver", to: driver_path(@conn, :new) %></span>
<h3><%= link "Go to vehicles list", to: vehicle_path(@conn, :list) %></h3>

web/templates/driver/new.html.eex
<h2>New driver</h2>

<%= render "form.html", changeset: @changeset,
                        action: driver_path(@conn, :create) %>

<span><%= link "Back", to: driver_path(@conn, :index) %></span>

web/templates/driver/show.html.eex
<h2>Show driver</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @driver.name %>
  </li>

  <li>
    <strong>Identification:</strong>
    <%= @driver.identification %>
  </li>

</ul>

<span><%= link "Edit", to: driver_path(@conn, :edit, @driver) %></span>
<span><%= link "Back", to: driver_path(@conn, :index) %></span>
<strong><%= link "Vehicles", to: driver_vehicle_path(@conn, :index, @driver) %></strong>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Registering!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to Drivers Registration System!" %></h2>
  <p class="lead">If you are a driver create your free driver account to get started.<br />Register your data in the link below.</p>
  <%= link "Sign Up", to: driver_path(@conn, :index) %>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/vehicle/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if f.errors != [] do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Kind</label>
    <%= text_input f, :kind, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>License Plate</label>
    <%= text_input f, :license_plate, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Brand</label>
    <%= text_input f, :brand, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/vehicle/index.html.eex
<h2>Listing vehicles for <%= @driver.name %></h2>

<table class="table">
  <thead>
    <tr>
      <th>License Plate</th>
      <th>Kind</th>
      <th>Brand</th>
    </tr>
  </thead>
  <tbody>
<%= for vehicle <- @vehicles do %>
    <tr>
      <td><%= vehicle.license_plate %></td>
      <td><%= vehicle.kind %></td>
      <td><%= vehicle.brand %></td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New vehicle", to: driver_vehicle_path(@conn, :new, @driver) %>

web/templates/vehicle/list.html.eex
<h2>Listing vehicles</h2>
<%= form_for @conn, vehicle_path(@conn, :list), [method: :get], fn f -> %>
  <%= text_input f, :license_plate, placeholder: "Search by license plate" %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>License Plate</th>
      <th>Brand</th>
      <th>Kind</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for vehicle <- @vehicles do %>
    <tr>
      <td><%= vehicle.license_plate %></td>
      <td><%= vehicle.brand %></td>
      <td><%= vehicle.kind %></td>

    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New driver", to: driver_path(@conn, :new) %></span>
<h3><%= link "Go to drivers list", to: driver_path(@conn, :index) %></h3>

web/templates/vehicle/new.html.eex
<h2>New vehicle for <%= @driver.name %></h2>

<%= render "form.html", changeset: @changeset,
                        action: driver_vehicle_path(@conn, :create, @driver) %>

<%= link "Back to vehicles", to: driver_vehicle_path(@conn, :index, @driver) %>